name: Sync Fork For Lookin
on:
  workflow_dispatch:
  schedule:
    - cron: 0 3 */1 * * # 每天凌晨3点执行

jobs:
  update_fork:
    runs-on: ubuntu-latest
    steps:
      - uses: QLCDFork/github-forks-sync-action@master
        with:
          github_token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          upstream_repository: hughkli/Lookin
          target_repository: QLCDFork/Lookin
          upstream_branch: Develop
          target_branch: Develop
          force: true
          tags: true
