name: Sync Fork For ColaCup
on:
  workflow_dispatch:
  push:
    branches:
      -master
  schedule:
    - cron: 0 3 */1 * * # 每天凌晨3点执行

jobs:
  update_fork_JSONPreview:
    runs-on: ubuntu-latest
    steps:
      - uses: TobKed/github-forks-sync-action@master
        with:
          github_token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          upstream_repository: rakuyoMo/ColaCup
          target_repository: QLCDFork/ColaCup
          upstream_branch: master
          target_branch: master
          force: true
          tags: true
